tap_install:
    sensitive_values:
        shared:
            ingress_domain: ENC[AES256_GCM,data:nmzGlnSEx6GK7/sn4VmDXH+7C9cc/dvkGmg7ENQbRgfJ08UB+Ntng3J30Wk=,iv:l6oDl01MXiPdXCS7SPQTgTBeKFE9G/H3wnx2v1yGQYU=,tag:6+9LHMknMC4cuRjwTv9yvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140kfw9jqh7d63svrgf8rpjaf8mteg507va4s98pnjtl975qe6stqfpaxvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVlNqTXd3L3NHdnJlZ1BC
            aWJuazBNY243L3h5aWJ1Z3VFV2ZVNE11V20wCng1YUlnZkxaYXNQcCs3UFhERmNG
            azlYR2JtM1BmdlpPOGxGYUUrMzYwOVkKLS0tIG5Ld1drajVHVW9PMWFoQk9nOFBL
            dTJPQUpScS91bGFXQmk0RUVqaGNEdmsKwEp8qSihKqe0vNZG8OVrPZuCPrzo74Ds
            sKwmF08Q8guNjRu2JCgDB8C6mtsyKqmJKw/4lrNgiZ8pGGWeKt1oTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-24T15:56:11Z"
    mac: ENC[AES256_GCM,data:/RlVH3p9cbmCX/cs7uCNMIQ6HUwx3ogo0ovZm0KJ3JCrejGKrYUetFAxTKQd4CN+1/9q4bX/Vqbwz50gtDynL9azXD2O82tWh2Sn/qqnbwz9hE+AozUqgCezwozDK+SHHehCo/scAvOsR6dhv6BnjeXWN1Z6Dtj6eYRF5j45Oz0=,iv:vOoh0Zt8aGkYGgKFlzOgQRF76+eVxUuxWqUHzH+/s4c=,tag:zCC0h4HC5k98LCCYyiBVGw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
